# Generated by Django 4.1.7 on 2024-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingOpportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp_id', models.CharField(max_length=255, unique=True)),
                ('opp_name', models.TextField()),
                ('pipeline_id', models.TextField()),
                ('pipeline_name', models.TextField()),
                ('stage_id', models.TextField()),
                ('stage_name', models.TextField()),
                ('monetary_value', models.TextField()),
                ('close_due_date', models.TextField()),
                ('actual_closed_date', models.TextField()),
                ('loan_type', models.TextField()),
                ('assigned_user_id', models.TextField()),
                ('assigned_user_name', models.TextField()),
                ('explanation', models.TextField()),
                ('how_many_times_lender_change', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalOpportunties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp_id', models.CharField(max_length=255, unique=True)),
                ('pipeline_id', models.TextField()),
                ('pipeline_name', models.TextField()),
                ('stage_id', models.TextField()),
                ('stage_name', models.TextField()),
            ],
        ),
    ]
