# Generated by Django 4.1.7 on 2024-08-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_processingopportunities_totalopportunties'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingopportunities',
            name='exists_in_ghl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='totalopportunties',
            name='exists_in_ghl',
            field=models.BooleanField(default=False),
        ),
    ]
