# Generated by Django 4.1.7 on 2024-08-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_processingopportunities_exists_in_ghl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingopportunities',
            name='original_close_due_date',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
