# Generated by Django 4.1.7 on 2024-08-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_processingopportunities_original_close_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingopportunities',
            name='actual_closed_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='assigned_user_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='assigned_user_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='close_due_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='how_many_times_lender_change',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='loan_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='monetary_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='opp_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='original_close_due_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='pipeline_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='pipeline_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='stage_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingopportunities',
            name='stage_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalopportunties',
            name='pipeline_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalopportunties',
            name='pipeline_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalopportunties',
            name='stage_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalopportunties',
            name='stage_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
