# Generated by Django 4.1.7 on 2024-08-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_processingopportunities_actual_closed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingopportunities',
            name='original_close_due_date',
            field=models.TextField(default=None),
        ),
    ]
