# Generated by Django 4.1.7 on 2024-08-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_processingopportunities_original_close_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingopportunities',
            name='original_close_due_date',
            field=models.TextField(default='N/A'),
        ),
    ]
