# Generated by Django 4.1.7 on 2024-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_processingopportunities_original_close_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingopportunities',
            name='original_close_due_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
